" Options
set autochdir
set autoindent
set autoread
set backspace=indent,eol,start
set cursorline
set expandtab
set foldlevel=4
set foldmethod=syntax
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set listchars=eol:$,tab:>-,space:.,trail:*
set nomodeline
set noshowcmd
set noshowmode
set noswapfile
set number
set relativenumber
set scrolloff=10
set shell=sh
set shiftwidth=2
set shortmess=flmrwxoOWF
set smartcase
set softtabstop=2
set splitbelow
set splitright
set tabpagemax=100
set termguicolors
set timeoutlen=200
set updatetime=1000
set wildmode=list:full

" Commands
colorscheme deep-space
syntax on

" MAPPINGS
" Source .vimrc
let vimrc_path = "~/.vim/vimrc"
nmap <Leader>, :execute 'tabedit' vimrc_path<CR>
nmap <Leader>. :execute 'source' vimrc_path<CR>

" Buffers
nmap gl :bnext<CR>
nmap gL :bprevious<CR>
nmap ZB :bdelete<CR>

" Useful actions
nmap <Leader>f :nohlsearch<CR>
nmap <Leader>l :set relativenumber!<CR>
nmap <Leader>s :set list!<CR>
nmap <Leader>t :%s/ \+$// <Bar> nohlsearch<CR>

" Disable arrow keys
map <Up> <Nop>
map <Down> <Nop>
map <Left> <Nop>
map <Right> <Nop>

" PLUGINS
" Netrw
let g:netrw_banner=0
let g:netrw_liststyle=3
let g:netrw_preview=1
let g:netrw_winsize=80

" Auto-pairs
let g:AutoPairsShortcutBackInsert='<Esc>b'
let g:AutoPairsShortcutFastWrap='<Esc>e'
let g:AutoPairsShortcutJump='<Esc>n'

" Disabled plugins
let g:loaded_matchparen=1

